ALTER SESSION SET CONTAINER = CDB$ROOT;
DROP USER C##USRDBZ_LOGMINER CASCADE;

ALTER SESSION SET CONTAINER = XEPDB1;
DROP TABLESPACE DBZTBLSPCLOGMINER;
ALTER SESSION SET CONTAINER = CDB$ROOT;
DROP TABLESPACE DBZTBLSPCLOGMINER;
