ALTER SESSION SET CONTAINER = CDB$ROOT;
ALTER SYSTEM ARCHIVE LOG CURRENT;

ALTER SESSION SET CONTAINER = XEPDB1;
CREATE TABLESPACE TBLS1 DATAFILE SIZE 100M AUTOEXTEND ON NEXT 100M;
ALTER TABLESPACE TBLS1 FORCE LOGGING;

CREATE USER USRTBL IDENTIFIED BY USRTBLPWD DEFAULT TABLESPACE TBLS1 TEMPORARY TABLESPACE TEMP;
ALTER USER USRTBL QUOTA UNLIMITED ON TBLS1;

GRANT CONNECT TO USRTBL;
GRANT RESOURCE TO USRTBL;

CREATE TABLE USRTBL.ADAM1(
    ID          NUMBER NOT NULL,
    NAME        VARCHAR2(30),
    COUNT       NUMBER,
    START_TIME0 TIMESTAMP(0),
    START_TIME3 TIMESTAMP(3),
    START_TIME6 TIMESTAMP(6),
    START_TIME9 TIMESTAMP(9)
);
ALTER TABLE USRTBL.ADAM1 ADD CONSTRAINT ADAM1PK PRIMARY KEY(ID);
ALTER TABLE USRTBL.ADAM1 ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

ALTER SESSION SET CONTAINER = CDB$ROOT;
ALTER SYSTEM ARCHIVE LOG CURRENT;
