CREATE TABLESPACE DBZTBLSPCLOGMINER DATAFILE SIZE 25M AUTOEXTEND ON MAXSIZE UNLIMITED;

ALTER SESSION SET CONTAINER = CDB$ROOT;
CREATE TABLESPACE DBZTBLSPCLOGMINER DATAFILE SIZE 25M AUTOEXTEND ON MAXSIZE UNLIMITED;

ALTER SESSION SET CONTAINER = CDB$ROOT;
CREATE USER C##USRDBZ_LOGMINER IDENTIFIED BY dbzpwd
  DEFAULT TABLESPACE DBZTBLSPCLOGMINER
  QUOTA UNLIMITED ON DBZTBLSPCLOGMINER
  CONTAINER = ALL;

ALTER SESSION SET CONTAINER = CDB$ROOT;
GRANT CREATE SESSION TO C##USRDBZ_LOGMINER CONTAINER=ALL;
GRANT CREATE TABLE TO C##USRDBZ_LOGMINER CONTAINER=ALL;
GRANT CREATE SEQUENCE TO C##USRDBZ_LOGMINER CONTAINER=ALL;
GRANT SET CONTAINER TO C##USRDBZ_LOGMINER CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE TO C##USRDBZ_LOGMINER CONTAINER=ALL;
GRANT EXECUTE_CATALOG_ROLE TO C##USRDBZ_LOGMINER CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO C##USRDBZ_LOGMINER CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY TO C##USRDBZ_LOGMINER CONTAINER=ALL;
GRANT SELECT ANY TABLE TO C##USRDBZ_LOGMINER CONTAINER=ALL;

GRANT LOGMINING TO C##USRDBZ_LOGMINER CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR TO C##USRDBZ_LOGMINER CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR_D TO C##USRDBZ_LOGMINER CONTAINER=ALL;

GRANT SELECT ON V_$LOG TO C##USRDBZ_LOGMINER CONTAINER=ALL;
GRANT SELECT ON V_$LOGFILE TO C##USRDBZ_LOGMINER CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO C##USRDBZ_LOGMINER CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO C##USRDBZ_LOGMINER CONTAINER=ALL;

ALTER SESSION SET CONTAINER = XEPDB1;
GRANT FLASHBACK ON USRTBL.ADAM1 TO C##USRDBZ_LOGMINER;
GRANT SELECT ON USRTBL.ADAM1 TO C##USRDBZ_LOGMINER;
