SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER SYSTEM ARCHIVE LOG CURRENT;

ALTER SYSTEM SET DB_CREATE_FILE_DEST = '/opt/oracle/oradata' SCOPE = BOTH;
ALTER SYSTEM SET DB_RECOVERY_FILE_DEST_SIZE = '250G' SCOPE = BOTH;
ALTER SYSTEM SET DB_RECOVERY_FILE_DEST = '/opt/oracle/fra' SCOPE = BOTH;
