CREATE USER USROLR IDENTIFIED BY USROLRPWD TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO USROLR;
GRANT RESOURCE TO USROLR;
GRANT SELECT, FLASHBACK ON SYS.CCOL$ TO USROLR;
GRANT SELECT, FLASHBACK ON SYS.CDEF$ TO USROLR;
GRANT SELECT, FLASHBACK ON SYS.COL$ TO USROLR;
GRANT SELECT, FLASHBACK ON SYS.DEFERRED_STG$ TO USROLR;
GRANT SELECT, FLASHBACK ON SYS.ECOL$ TO USROLR;
GRANT SELECT, FLASHBACK ON SYS.LOB$ TO USROLR;
GRANT SELECT, FLASHBACK ON SYS.LOBCOMPPART$ TO USROLR;
GRANT SELECT, FLASHBACK ON SYS.LOBFRAG$ TO USROLR;
GRANT SELECT, FLASHBACK ON SYS.OBJ$ TO USROLR;
GRANT SELECT, FLASHBACK ON SYS.TAB$ TO USROLR;
GRANT SELECT, FLASHBACK ON SYS.TABCOMPART$ TO USROLR;
GRANT SELECT, FLASHBACK ON SYS.TABPART$ TO USROLR;
GRANT SELECT, FLASHBACK ON SYS.TABSUBPART$ TO USROLR;
GRANT SELECT, FLASHBACK ON SYS.TS$ TO USROLR;
GRANT SELECT, FLASHBACK ON SYS.USER$ TO USROLR;
GRANT SELECT ON SYS.V_$ARCHIVED_LOG TO USROLR;
GRANT SELECT ON SYS.V_$DATABASE TO USROLR;
GRANT SELECT ON SYS.V_$DATABASE_INCARNATION TO USROLR;
GRANT SELECT ON SYS.V_$LOG TO USROLR;
GRANT SELECT ON SYS.V_$LOGFILE TO USROLR;
GRANT SELECT ON SYS.V_$PARAMETER TO USROLR;
GRANT SELECT ON SYS.V_$STANDBY_LOG TO USROLR;
GRANT SELECT ON SYS.V_$TRANSPORTABLE_PLATFORM TO USROLR;
GRANT SELECT, FLASHBACK ON XDB.XDB$TTSET TO USROLR;
DECLARE
CURSOR C1 IS SELECT TOKSUF FROM XDB.XDB$TTSET;
CMD VARCHAR2(2000);
BEGIN
FOR C IN C1 LOOP
        CMD := 'GRANT SELECT, FLASHBACK ON XDB.X$NM' || C.TOKSUF || ' TO USROLR';
EXECUTE IMMEDIATE CMD;
CMD := 'GRANT SELECT, FLASHBACK ON XDB.X$QN' || C.TOKSUF || ' TO USROLR';
EXECUTE IMMEDIATE CMD;
CMD := 'GRANT SELECT, FLASHBACK ON XDB.X$PT' || C.TOKSUF || ' TO USROLR';
EXECUTE IMMEDIATE CMD;
END LOOP;
END;
/

ALTER SESSION SET CONTAINER = CDB$ROOT;
ALTER SYSTEM ARCHIVE LOG CURRENT;
