ALTER SESSION SET CONTAINER = CDB$ROOT;
DROP USER C##USRDBZ_OLR CASCADE;

ALTER SESSION SET CONTAINER = XEPDB1;
DROP TABLESPACE DBZTBLSPCOLR;
ALTER SESSION SET CONTAINER = CDB$ROOT;
DROP TABLESPACE DBZTBLSPCOLR;
