ALTER SESSION SET CONTAINER = CDB$ROOT;
ALTER SYSTEM ARCHIVE LOG CURRENT;

ALTER SESSION SET CONTAINER = XEPDB1;
CREATE TABLESPACE TBLS1 DATAFILE SIZE 100M AUTOEXTEND ON NEXT 100M;
ALTER TABLESPACE TBLS1 FORCE LOGGING;

CREATE USER USRTBL IDENTIFIED BY USRTBLPWD DEFAULT TABLESPACE TBLS1 TEMPORARY TABLESPACE TEMP;
ALTER USER USRTBL QUOTA UNLIMITED ON TBLS1;

GRANT CONNECT TO USRTBL;
GRANT RESOURCE TO USRTBL;

ALTER SESSION SET CONTAINER = CDB$ROOT;
ALTER SYSTEM ARCHIVE LOG CURRENT;
