DROP USER USR1 CASCADE;
DROP USER USR2 CASCADE;

ALTER SESSION SET CONTAINER = XEPDB1;
DROP TABLESPACE TBLS1 INCLUDING CONTENTS AND DATAFILES;

ALTER SESSION SET CONTAINER = CDB$ROOT;
ALTER SYSTEM ARCHIVE LOG CURRENT;

ALTER SESSION SET CONTAINER = XEPDB1;
CREATE TABLESPACE TBLS1 DATAFILE SIZE 100M AUTOEXTEND ON NEXT 100M;
ALTER TABLESPACE TBLS1 FORCE LOGGING;

CREATE USER USR2 IDENTIFIED BY USR2PWD DEFAULT TABLESPACE TBLS1 TEMPORARY TABLESPACE TEMP;
ALTER USER USR2 QUOTA UNLIMITED ON TBLS1;

GRANT CONNECT TO USR2;
GRANT RESOURCE TO USR2;

ALTER SESSION SET CONTAINER = CDB$ROOT;
ALTER SYSTEM ARCHIVE LOG CURRENT;
